language: php

php:
  - '7.0'

services:
  - mongodb

matrix:
  fast_finish: true
  include:
    - php: '7.0'
      env: MONGO_EXT_VERSION="1.1.8"
    - php: '7.0'
      env: SYMFONY=2.8.*
    - php: '7.0'
      env: SYMFONY=3.0.*
    - php: '7.0'
      env: SYMFONY=3.1.*
    - php: '7.0'
      env: SYMFONY=3.2.*
    - php: '7.0'
      env: SYMFONY=dev-master
    - php: '7.0'
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - env: SYMFONY=dev-master
    - env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer config --quiet --global github-oauth.github.com ${GITHUB_OAUTH_TOKEN}
  - if [ "$SYMFONY" != "" ]; then composer require "symfony/symfony:${SYMFONY}" --no-update; fi;

install:
  - if [ "$MONGO_EXT_VERSION" != "" ]; then pecl install -f mongodb-${MONGO_EXT_VERSION}; fi;
  - if [ "$MONGO_EXT_VERSION" = "" ]; then echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - mkdir --parents "${HOME}/bin"
  - composer update --prefer-dist --prefer-stable --no-interaction ${COMPOSER_FLAGS}

before_script:
  - echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer validate
  - bin/phpunit -c ./phpunit.xml.dist --coverage-clover=./build/coverage/coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar --output-document="${HOME}/bin/ocular" && chmod +x "${HOME}/bin/ocular"
  - ocular code-coverage:upload --format=php-clover ./build/coverage/coverage.clover

notifications:
  on_success: never
  on_failure: always
